# Generated by Django 5.1.2 on 2024-10-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_claude_key_user_llm_type_user_openai_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='claude_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='openai_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
