# Generated by Django 5.1.2 on 2024-10-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_rename_message_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('ai', 'AI'), ('human', 'User')], default='human', max_length=20),
        ),
    ]
