# Generated by Django 5.1.2 on 2024-10-20 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_conversations', '0001_initial'),
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message_conversation', to='chat_messages.message'),
        ),
    ]
