# Generated by Django 5.1.2 on 2024-10-20 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_conversations', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='name',
            new_name='title',
        ),
    ]
