# Generated by Django 5.1.2 on 2024-10-20 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_conversations', '0004_rename_name_conversation_title'),
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_conversation', to='chat_messages.message'),
        ),
    ]
