# Generated by Django 5.1.2 on 2024-10-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_conversations', '0006_conversation_embed_url_alter_conversation_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='charges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
